### ISSUE TITLE
no docs

### ISSUE THREAD

**Issue by Kamar-Meddah** [SpringNyan/vue-typescript-inject#1]
hello, i wish if there was a documentation on how to use the library

**Comment by SpringNyan** [comment]
Hi @Kamar-Meddah, sorry for the late reply.
I have published a new version of this library and updated README. You can check it for basic usage.

**Comment by Kamar-Meddah** [comment]
hi @SpringNyan 
thx for providing us with docs 
ur library is very simple and useful continue working on it (y)
