### ISSUE TITLE
Error in beforeCreate hook

### ISSUE THREAD

**Issue by Malik19051992** [SpringNyan/vue-typescript-inject#2]
Faced with the next issue. Can't resolve.
Have 3 services: 
```
import {injectable} from "vue-typescript-inject";

@injectable()
export class LocalStorageService {
  public set(key: string, value: any): void {
    ...
  }

  public get(key: string): any {
    ...
  }
}

@injectable()
export class StoreService {
  constructor() {}

  public dispatch(storeNamespace: any, storeAction: any, payload?: any): void {
    ...
  }
}

@injectable()
export class LoginService {
  constructor(private storeService: StoreService,
                     private localStorageService: LocalStorageService) {}
  }
}
```

and have next error 
![image](https://user-images.githubusercontent.com/25901553/64796784-eb368c80-d588-11e9-8c2f-85f60a9cee01.png)

**Comment by Malik19051992** [comment]
I found the core of the issue. I have this error when try to inject service1 in service2 and not inject service1 in the component. I think if you delete line `  @inject() private readonly _serviceA!: ServiceA; // same as @inject(ServiceA)` from the example you get the same error

**Comment by SpringNyan** [comment]
@Malik19051992 I still can't repro it. I have released 0.3.0 with improved error message, you can use it to find out which class cause the error.

**Comment by SpringNyan** [comment]
@Malik19051992 I found the root cause. Please only write `import "reflect-metadata";` once at the top of your `index.ts`. For more details, see https://www.typescriptlang.org/docs/handbook/decorators.html#metadata

**Comment by Malik19051992** [comment]
> @Malik19051992 I found the root cause. Please only write `import "reflect-metadata";` once at the top of your `index.ts`. For more details, see https://www.typescriptlang.org/docs/handbook/decorators.html#metadata

thanks. I found `import "reflect-metadata"` in one of my services
