### ISSUE TITLE
Does this lib support singletons?

### ISSUE THREAD

**Issue by webnoob** [SpringNyan/vue-typescript-inject#4]
As the title says :)

The docs say to check angulars docs for usage and Angular supports via `@Injectable({ providedIn: 'root' })`.

I'd like to register my ApolloClient as a singleton as it contains its own caching and having new versions for each component wouldn't make sense.

**Comment by SpringNyan** [comment]
@webnoob  You can register singleton providers in the root component, and then inject them in the child components.
